image: registry.gitlab.com/pages/hugo/hugo_extended:0.104.3

variables:
  HUGO_ENV: production

default:
  before_script:
    - hugo mod get gitlab.com/rs-site/rs-theme

pages:
  script:
    - hugo mod get gitlab.com/rs-site/rs-theme
    - hugo
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
