baseURL = 'https://rework-space.com'
title = 'Rework-Space'
#theme = ["rs-theme"]
theme = ["gitlab.com/rs-site/rs-theme"]

DefaultContentLanguage = "en"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "G-YCZWM6D5L1"
enableRobotsTXT = true

[languages]
  [languages.en]
    languageCode = 'en'
    title = "Rework-Space"
    weight = 1
    contentDir = "content/en"
    footerContactButton = "Contact us"
    footerContactButtonPath = '/about/contacts/'
    footerPrivacy = 'Privacy'
    footerPrivacyUrl = '/about/privacy'
    customFooterLine1 = "10 Berezhans'ka St, office 82"
    customFooterLine2 = '46027, Ternopil, Ukraine'
    customFooterLine3 = '+38 067 324 6141'
    read_more_button = 'Read more ->'
    date_prefix = 'Published #'
  [languages.ua]
    languageCode = 'uk'
    title = "Rework-Space"
    weight = 2
    contentDir = "content/ua"
    footerContactButton = "Зв'яжіться з нами"
    footerContactButtonPath = '/ua/about/contacts/'
    footerPrivacy = 'Конфіденційність'
    footerPrivacyUrl = '/about/privacy'
    customFooterLine1 = 'вул. Бережанська 10, офіс 82'
    customFooterLine2 = 'м.Тернопіль, 46027,  Україна'
    customFooterLine3 = '+38 068 699 3913'
    read_more_button = 'Детальніше ->'
    date_prefix = 'Опубліковано #'

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  middle_title_color_code = "#008080"
  link_color = "#008080"
  author = ""
  favicon = '/general-images/rework_logo.webp'
  siteLogo = '/general-images/rework_logo_10grey_008080.webp'
  header_image = '/general-images/background_photo_line.webp'
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-mid-gray" # header and footer default background color
  body_classes = "avenir bg-white" # font and body background color
  recent_posts_number = 3
  date_format = '2006-01-02'
  post_content_classes = "avenir"

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/rework_space"
